### ISSUE TITLE
Bootstrap error at MacOS

### ISSUE THREAD

**Issue by 6ugman** [vxgmichel/aioconsole#15]
I cant run the command at MacOS, there are outputs:
```
❯ apython
Python 3.6.3 (default, Nov 23 2017, 18:02:45)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
---
This console is running in an asyncio event loop.
It allows you to wait for coroutines using the 'await' syntax.
Try: await asyncio.sleep(1, result=3)
---
Traceback (most recent call last):
  File "/usr/local/bin/apython", line 11, in <module>
    sys.exit(run_apython())
  File "/usr/local/lib/python3.6/site-packages/aioconsole/apython.py", line 57, in run_apython
    code = run_apython_in_subprocess(args)
  File "/usr/local/lib/python3.6/site-packages/aioconsole/apython.py", line 102, in run_apython_in_subprocess
    raw = input_with_stderr_prompt(prompt) + '\n'
  File "/usr/local/lib/python3.6/site-packages/aioconsole/apython.py", line 144, in input_with_stderr_prompt
    fin = ctypes.c_void_p.in_dll(api, 'stdin')
ValueError: dlsym(RTLD_DEFAULT, stdin): symbol not found
```
It is my os problem?

**Comment by kelbyers** [comment]
Mac OS X does not provide 'stdin', 'stdout', or 'stderr' symbols in its export libraries. It turns out that the symbols are named: '__stdinp', '__stdoutp', and '__stderrp'.

I have created a PR with a fix (and tests) for this: #16

**Comment by vxgmichel** [comment]
Thanks for the report! PR #16 is merged, I'll release version `0.1.6` soon. In the meantime, you can use `apython --no-readline`.
