### ISSUE TITLE
0.1.9 fails with TypeError (Python 3.6)

### ISSUE THREAD

**Issue by berekuk** [vxgmichel/aioconsole#29]
```
$ apython
Traceback (most recent call last):
  File "/Users/berekuk/.local/share/virtualenvs/core--9goXGUj/bin/apython", line 11, in <module>
    sys.exit(run_apython())
  File "/Users/berekuk/.local/share/virtualenvs/core--9goXGUj/lib/python3.6/site-packages/aioconsole/apython.py", line 90, in run_apython
    code = run_apython_in_subprocess(args, namespace.prompt_control)
  File "/Users/berekuk/.local/share/virtualenvs/core--9goXGUj/lib/python3.6/site-packages/aioconsole/apython.py", line 139, in run_apython_in_subprocess
    proc_args + args,
TypeError: can only concatenate list (not "NoneType") to list
```

Downgrading to 0.1.8 fixes this issue.

**Comment by vxgmichel** [comment]
Ergh, I can't believe I let such an obvious bug slip into the 0.1.9 release...

Anyway, it's fixed (PR #30). I removed 0.1.9 from PyPI and released the fix as [v0.1.10](https://pypi.org/project/aioconsole/0.1.10/).

Thanks very much for the report and sorry for the inconvenience.
