### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by ekevoo** [vxgmichel/aioconsole#4]
![image](https://cloud.githubusercontent.com/assets/871714/26665664/49a294b4-4669-11e7-9ec6-521ee471c381.png)

The "apython" command installs itself normally in Windows, as it's also added to %PATH%, but it shows nothing. I've also tried to type "exit()" blind to see if it's just an output problem, but apparently it's also an input problem.

I'll try to investigate further in the next few days, but I saw no mention of support of lack thereof anywhere, so I decided a heads-up issue was in order... Just in case I'm missing something obvious, or maybe it's a just documentation bug. :)

**Comment by vxgmichel** [comment]
Thanks for the report!

I actually never had the opportunity to test the project on windows :)

Could you try to run the following example?

```python
import asyncio
from aioconsole import ainput

async def main():
    name = await ainput("What's your name?\n>>> ")
    print(f"Hello {name.strip()}!")

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

**Comment by ekevoo** [comment]
It runs fine on IDLE. Not so much on the command-line.

```
C:\Users\obalbuena\Desktop>python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    loop.run_until_complete(main())
  File "C:\Users\obalbuena\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "test.py", line 5, in main
    name = await ainput("What's your name?\n>>> ")
  File "C:\Users\obalbuena\AppData\Local\Programs\Python\Python36\lib\site-packages\aioconsole\stream.py", line 147, in ainput
    reader, writer = yield from get_standard_streams(loop=loop)
  File "C:\Users\obalbuena\AppData\Local\Programs\Python\Python36\lib\site-packages\aioconsole\stream.py", line 135, in get_standard_streams
    cache[key] = yield from connection
  File "C:\Users\obalbuena\AppData\Local\Programs\Python\Python36\lib\site-packages\aioconsole\stream.py", line 123, in create_standard_streams
    reader, writer = yield from future
  File "C:\Users\obalbuena\AppData\Local\Programs\Python\Python36\lib\site-packages\aioconsole\stream.py", line 106, in open_pipe_connection
    yield from loop.connect_read_pipe(lambda: protocol, pipe_in)
  File "C:\Users\obalbuena\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1097, in connect_read_pipe
    transport = self._make_read_pipe_transport(pipe, protocol, waiter)
  File "C:\Users\obalbuena\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 328, in _make_read_pipe_transport
    raise NotImplementedError
NotImplementedError
```

**Comment by vxgmichel** [comment]
Thank you for taking the time to run those tests, 596ac7b should now help. Could try again with version 0.1.3dev0 (latest on the master branch)?

**Comment by ekevoo** [comment]
That did the trick! Thanks :)

![image](https://cloud.githubusercontent.com/assets/871714/26690307/c5793af4-46c6-11e7-8d39-76165819d9e2.png)

![image](https://cloud.githubusercontent.com/assets/871714/26690308/c94af384-46c6-11e7-9280-9c2bbac04679.png)

**Comment by vxgmichel** [comment]
Great, thank you for your help!
