### ISSUE TITLE
UnicodeEncodeError when running apython on Ubuntu 18.04

### ISSUE THREAD

**Issue by JonasVautherin** [vxgmichel/aioconsole#53]
Running `apython` from `aioconsole-0.1.14` on an Ubuntu 18.04 docker container, I get the following error:

```
# apython
Traceback (most recent call last):
  File "/usr/local/bin/apython", line 11, in <module>
    sys.exit(run_apython())
  File "/usr/local/lib/python3.6/dist-packages/aioconsole/apython.py", line 97, in run_apython
    code = run_apython_in_subprocess(args, namespace.prompt_control)
  File "/usr/local/lib/python3.6/dist-packages/aioconsole/apython.py", line 153, in run_apython_in_subprocess
    use_stderr=True)
  File "/usr/local/lib/python3.6/dist-packages/aioconsole/rlwrap.py", line 24, in rlwrap_process
    **{'stderr' if use_stderr else 'stdout': subprocess.PIPE})
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u200b' in position 0: ordinal not in range(128)
```

Running the same version on Arch Linux (installed from pip) works, though.

Why could that be?

**Comment by vxgmichel** [comment]
Hi @JonasVautherin,

Can you run this :
```python
import sys
print(sys.getfilesystemencoding())
```

I suspect this issue to be related to the locale configuration of your docker image, maybe have a look at this post?
- [How to set the locale inside a Ubuntu Docker container?](https://stackoverflow.com/a/28406007/2846140)

You can also use `apython --no-readline` as a workaround.

Thanks for the report!

**Comment by vxgmichel** [comment]
Hi @JonasVautherin,

Can you run this :
```python
import sys
print(sys.getfilesystemencoding())
```

I suspect this issue to be related to the locale configuration of your docker image, maybe have a look at this post?
- [How to set the locale inside a Ubuntu Docker container?](https://stackoverflow.com/a/28406007/2846140)

You can also use `apython --no-readline` as a workaround.

Thanks for the report!

**Comment by vxgmichel** [comment]
I'm closing this issue because of inactivity. 

@JonasVautherin Feel free to re-open it if you're still facing this problem :)
