### ISSUE TITLE
bug: automatically import any `queue.py` from the same directory.

### ISSUE THREAD

**Issue by rendarz** [vxgmichel/aioconsole#86]
Hello, I have just discovered an aioconsole bug:
If I run a program which imports aioconsole, and in the same directory of that program there will be a file called `queue.py`, that
file, whatever it contains, it will be imported too, causing A LOT of bugs.
I've spent 2 hrs to figure out that the strange behavior I was getting was due to this.

I will share a screenshot to show you a simple snippet of this unwanted behavior.

NOTE: In the screenshot, `py` is just an alias for `python` which I use in my shell.

Thank you for your time.
![Screenshot_2021-08-24_10-38-24](https://user-images.githubusercontent.com/12814431/130586140-fe731ce0-9e38-4425-b807-caa9bd5afe42.png)

**Comment by vxgmichel** [comment]
Hi @rendarz and thanks for the report!

It turns out you just ran into the [name shadowing trap](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap). You can replace the content of prompt with:
```python
from concurrent.futures import ThreadPoolExecutor
ThreadPoolExecutor()
```
and note that the problem still occurs, and also the following trace is produced:
```
  File "/home/vinmic/repos/test.py", line 2, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/vinmic/miniconda/lib/python3.9/concurrent/futures/__init__.py", line 49, in __getattr__
    from .thread import ThreadPoolExecutor as te
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/vinmic/miniconda/lib/python3.9/concurrent/futures/thread.py", line 10, in <module>
    import queue
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/vinmic/repos/queue.py", line 3, in <module>
    traceback.print_stack()
Traceback (most recent call last):
  File "/home/vinmic/repos/test.py", line 3, in <module>
    ThreadPoolExecutor()
  File "/home/vinmic/miniconda/lib/python3.9/concurrent/futures/thread.py", line 144, in __init__
    self._work_queue = queue.SimpleQueue()
AttributeError: module 'queue' has no attribute 'SimpleQueue'
```
.. making it more obvious that the standard library module `queue` has been shadowed. The solution is simply to not have a local module module with the same name as a standard library module.

Since it's unrelated to aioconsole I'm closing the issue :)

**Comment by rendarz** [comment]
Thanks for your help, that's clear now. :)
